### PR TITLE
Use rust tls for reqwest

### PR DESCRIPTION
**Pull request by ArthurZhou**
using rust tls for reqwest

in order to build for android

### CODE REVIEW

**Comment by idootop** [comment]
@ArthurZhou Thanks for your contribution ❤️. Please make sure to keep the example code as is.

**Comment by ArthurZhou** [comment]
my bad :)

**Comment by idootop** [comment]
LGTM. I will test it shortly and release an updated version asap.

**Comment by idootop** [comment]
@ArthurZhou  v3.1.0 was released: https://github.com/idootop/tauri-plugin-cors-fetch/releases/tag/v3.1.0

**Pull request merged**
